#Change me to change the display tag for plugin related messages
Plugin Tag: "&8[&cHousing&8] &7"

# This is the number of houses players may own, set to -1 to not limit.
houseLim: 1

# This controls whether or not your buycraft will be plugged, edit the message below to edit the buycraft link.
plugBuycraft: true

# Messages: Change these to change the different messages given to the players
# use %price% for the price of extention or house,
# use %player% for the player name
# use %inc% for the time incrementation
# use %unit% for the unit of incrementation Ex. Days, Months, Seconds...
# use %reg% for the house's name/ World Guard region.

buycraftAd: "&7Upgrade your rank today to unlock access to rent houses and more using /buy!"
errCantExt: "&7You &ccannot &7extend your rent further."
errCantBuy: "&7You &cdo not &7have permission to rent houses."
errRegNoExist: "&7The house &b%reg%&7 &cdoesn't&7 exist!"
errTimeNotNumber: "&7The &blast value &7must be the &atime &7in &adays &7the region is &asold &7after."
errPriceNotNumber: "&7The &b3rd value &7must be the &aprice &7the region is &asold \n&7for per time quantity specified by the next line."
errPlyrNotExist: "&7The player &b%plr% &7does not exist."
errRegAlrExist: "&7The house &b%reg%&7 already exists!"
errNotInRegion: "&7You are not within the house &b%reg%&7."
errNotOwner: "&7You are not the owner of the house &b%reg%&7."
errBlacklisted: "&7You may not enter this house!"
errAlrBlacklisted: "&7The &b%plr%&7 is &aalready&7 blacklisted from the house &b%reg%&7."
errNotBlacklisted: "&7The &b%plr%&7 is &anot&7 blacklisted from the house &b%reg%&7."
errNotMem: "&7The &b%plr%&7 is &anot&7 a member of this house."
errAlrMem: "&7The &b%plr%&7 is &aalready&7 a member of this house."
rentTime: "&7This house will expire in: &a%time%&7."
forRentTag: "&fFOR RENT"
occupiedTag: "&fOCCUPIED"
blPlr: "&7The player &b%plr%&7 has been blacklisted from the house &b%reg%&7."
unBlPlr: "&7The player &b%plr%&7 has been unblacklisted from the house &b%reg%&7."
forceSetOwner: "&7You have set the &b%reg%&7's owner to &b%plr%&7"
errAlreadyOwner: "&7The player &b%plr%&7 is already the &b%reg%&7's owner."
playerSetOwner: "&7You have been assigned the house &b%reg%&7."
forceSetSpawn: "&7You have force set &b%reg%'s spawn to &a%x%&7, &a%y%&7, &a%z%&7."
playerSetSpawn: "&7The house &b%reg%&7's spawn to &a%x%&7, &a%y%&7, &a%z%&7."
forceAddPlayer: "&7The player &b%plr%&7 has been force added to your house &b%reg%&7."
forceAddPlayerAdmin: "&7The player &b%plr%&7 has been force added to the region &b%reg%&7."
errPlayerAlreadyAdded: "&7The player &b%plr%&7, is already added to the region &b%reg%&7."
forceRemPlayer: "&7The player &b%plr%&7 has been force removed from your house &b%reg%&7."
forceRemPlayerAdmin: "&7The player &b%plr%&7 has been force removed from the region &b%reg%&7."
errPlrNotAdded: "&7The player &b%plr%&7, is not added to the region &b%reg%&7."
forceAddTimePlayer: "&7Your house, &b%reg%&7, had its time left in days has been updated to: &a%time%"
forceAddTimeAdmin: "&7The house &b%reg%&7, had its time left in days has been updated to: &a%time%"
forceChangePrice: "&7The house &b%reg%&7 is now worth &a$%price%&7 for a period of &b%time%&7."
playerChangePrice: "&7Your house &b%reg%&7 is now worth &a$%price%&7 for a period of &b%time%&7."
refundToPlayer: "&7You &7have been refunded &a%refund%&7 because your house was force unrented."
refundToAdmin: "&b%plr% &7has been refunded &a%refund%&7."
priceTag: "&c&l- $%price%"
sellHouse: "&7Your house has been &asold&7!"
buyHouse: "&7You've &abought &7this lovely house for &a%price%&7!"
addToHouse: "&7You've &aadded &b%player% &7to your house!"
removeFromHouse: "&7You've &cremoved &b%plr% &7from house &b%reg%&7!"
extRent: "&7You've extended your rent by %inc% %unit%&7: s)!"
permBuy: "&7You've &lPerminantly &a&lBought &7this house for &a%price%&7!"
remHouse: "&7You've &cremoved&7 the house &b%reg%&7."
creHouse: "&7You've &acreated&7 the house &b%reg%&7."

# Permissions: Change these to change the name of the permission node required to do specific tasks
# for playerAddLimit, this permission can be changed to check the amount of members a player can have
# added at any one time, change the value after the '.' to change how many, use '*' to allow unlimited.
houseRentPerm: "houses.rent"
aptRent: "apt.rent"
playerAddLimit: "houses.add."
houseAdmin: "houses.admin"